# Generated by Django 4.0.4 on 2022-08-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitngUsers',
            fields=[
                ('roomName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userNum', models.IntegerField(default=0)),
            ],
        ),
    ]
