# Generated by Django 4.0.4 on 2022-08-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jissyu3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitngusers',
            name='userNum',
            field=models.IntegerField(default=1),
        ),
    ]
