# Generated by Django 4.0.4 on 2022-09-01 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jissyu3', '0003_waitingrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingRooms',
            fields=[
                ('roomName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 9, 1, 10, 16, 8, 933926, tzinfo=utc))),
            ],
        ),
    ]
