# Generated by Django 4.0.4 on 2022-10-09 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jissyu3', '0004_playingrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitngusers',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 13, 44, 29, 959950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playingrooms',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 13, 44, 29, 960571, tzinfo=utc)),
        ),
    ]
