# Generated by Django 4.1.2 on 2022-10-10 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jissyu3', '0005_waitngusers_createtime_alter_playingrooms_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playingrooms',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 6, 23, 45, 478970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waitngusers',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 6, 23, 45, 478200, tzinfo=datetime.timezone.utc)),
        ),
    ]
